export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  VENDOR_NOT_FOUND: "VENDOR_NOT_FOUND",
  RESCHEDULE_CONFLICT: "RESCHEDULE_CONFLICT",
  BATCH_RESCHEDULE_FAILED: "BATCH_RESCHEDULE_FAILED"
} as const;
